### ISSUE TITLE
Proper Use of Layout Component

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/newalkalisite#19]
@ogdenstudios

I created a reusable layout component, TwoColumnLayoutTwo which will always have two child props passed into it. I just want to double check that I did everything correctly or if there is any room for improvement. The parent component with child components are placed [here](https://github.com/baudoinalkali/newalkalisite/blob/a068cad8d5022dd0a3acca053bc004216aa697c9/pages/clients/carro.tsx#L58-L77). The component itself is [here](https://github.com/baudoinalkali/newalkalisite/blob/a068cad8d5022dd0a3acca053bc004216aa697c9/components/TwoColumnLayoutTwo.tsx#L1-L14).

**Comment by ogdenstudios** [comment]
Yeah, you nailed it! I think I may have sent this link when I first introduced it, but you're basically using [composition as intended](https://reactjs.org/docs/composition-vs-inheritance.html). Good job there. 

I'm going to open a very quick PR with one improvement for you to consider, but you certainly got the principle correctly.

**Comment by baudoinalkali** [comment]
JSX to Constant example: https://github.com/baudoinalkali/newalkalisite/pull/28/commits/90344160d6b1cedacf3488007bc39693d46276ef
