### ISSUE TITLE
<Link href=""> vs <a href="">

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/newalkalisite#23]
@ogdenstudios

Which one should I be using? Is there a benefit of using one over the other or am I overthinking it?

**Comment by ogdenstudios** [comment]
The `Link` tag is the [`next/link` component](https://nextjs.org/docs/api-reference/next/link), which is a Next.js specific React component that allows for client side page transitions. 

`a` is the [semantic HTML anchor tag](https://www.w3schools.com/tags/tag_a.asp). 

You should use `Link` if and when you want page-to-page transitions. Keep in mind, there is technically a performance implication of using that. It's very small, so I wouldn't sweat it, but I know you care a lot about the performance. Using anchor tags will be faster usually. 

`Link` tags also won't do anything for you for external links. They only enable transitions between pages on your Next site. So you should definitely use `<a>` for external links. 

You're not overthinking it, there is a meaningful difference between the two, and you'll just have to make the choice of when you want to have page-to-page transitions.

**Comment by baudoinalkali** [comment]
@ogdenstudios Understood.
