### ISSUE TITLE
Website Header Variation | RESOLVE If Statement to Change Component Structure BEFORE THIS

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/newalkalisite#24]
@ogdenstudios

This is a bit down the road, but the website will have to header variations, one is all white (white logo and white text), the other is all blue. How would you recommend going about structuring that? Currently I just have to different Header Props and assign them on a per page basis according to how I want it to look? I now know I can restructure this to only have one and then have a prop defining which one to use (assuming my previous if scenario issue is okay to continue reusing), is there another way you would recommend doing that?

**Comment by ogdenstudios** [comment]
If the only difference is the logo and text colors, I would just use props to conditionally switch the `className` values you're using. 

But I know some websites have semantically different headers (meaning the content and markup is different). If that's the case, you'll probably want to do some conditional rendering, or even write them as separate components entirely. 

If that's out of scope, then you should be perfectly fine with conditional `className` values.

**Comment by baudoinalkali** [comment]
@ogdenstudios Yea it's just that, so I'll do that. I would use the same inline if/else that you informed me of correct? That way I can have it all under a single Header component.

**Comment by ogdenstudios** [comment]
Correct - inline should be plenty fine for this. It's up to you if you write it and find it's a little clunky whether or not you want to abstract it out to a function.
