### ISSUE TITLE
Did I Go Too Far?

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/newalkalisite#40]
@ogdenstudios

I ended up reformatting the Header component to change color depending on the prop value.  I recall you saying that if I was just changing the text and logo color it would make sense to keep it in a single component instead of having two header components. I forgot that color is spread throughout a few different places so I ended up having to do [this](https://github.com/baudoinalkali/newalkalisite/blob/cd241877544e78353562bf23247146f98f7bdf63/components/Header.tsx#L6-L18). My biggest question is did I have to declare too many consts in the header to have it make more sense to have two separate Header components? In addition I also created a data file for the links and a SiteMapContainer component so that I could easily reuse this in the Footer later on. I more so did this to easily be able to update all the links throughout. Does doing so on something that is used throughout the entire site have any negative implications?

**Comment by ogdenstudios** [comment]
You definitely didn't go too far here. This is probably exactly what I would do if I was handling all of this at once. 

No negative implications for your footer data file. This is looking good.

**Comment by baudoinalkali** [comment]
Great, I have some fine tuning to do with respect to styling, but just wanted to make sure having that many consts was something to be avoided before diving more into it.
