### ISSUE TITLE
Opinion on Refactoring

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/newalkalisite#43]
@ogdenstudios

Had another opportunity to create a more usable component, just wanted to get your advice on if there is any room for improvement. I originally had an AngledImage component that supported two angle types. I was going to make a new Image component, but realized I could do what you introduced me to. The new component StandardImage, can be found [here](https://github.com/baudoinalkali/newalkalisite/blob/15c1bfc5e22bccd4468058cd6d987f3ecf641624/components/StandardImage.tsx).

**Comment by ogdenstudios** [comment]
This is perfect. I wouldn't change much, except I would use `===` instead of `==` in line 8, the return statement of `imageContainerAngle`.
