### ISSUE TITLE
Thoughts on Organizing Components

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/newalkalisite#44]
@ogdenstudios

I imagine this is highly subjective, but do you have any advice on how to best organize components?

I was thinking of breaking it up into the following paths:
/sitewide (TwoColumnLayout, Header, Footer, etc)
/services (Service Header, CTA unique to services, ResponsiveScreens, etc)
/clients (ClientCard, ClientCardContainer, etc)
/auxiliary (About, Contact, etc)

**Comment by ogdenstudios** [comment]
You're right to identify this as highly subjective. One of the areas React is weakest in is opinions on project structure. I usually end up changing mine pretty frequently. 

The best place to start is exactly where you are now: set it up so it makes sense to you to begin, and just be willing to adjust it if and when it no longer makes sense, or if you end up bringing in collaborators who have trouble finding their way.
