### ISSUE TITLE
Map Into Grid

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/newalkalisite#63]
@ogdenstudios

I think this is somewhat similar to a previous issue, but I tried looking at the code you made to repurpose it, but seems it is different since in this use case it would be mapping a component. I currently have a faq component set up in a recent pull request (FAQDropdown.tsx). I have it set up to where if I copy the Disclosure component it will display it side by side to the current one in a grid. I tried setting up map on the /services/web-development/wordpress-website-development page, but can't seem to pass it inside a <div> to get it side by side.

**Comment by ogdenstudios** [comment]
Hey @baudoinalkali - I should be able to take a look at this tomorrow. Will you please tag me in an inline code comment or in the specific PR?

**Comment by baudoinalkali** [comment]
@ogdenstudios This is the PR https://github.com/baudoinalkali/newalkalisite/pull/62, it isn't letting me link to specific lines in the files changed tab, is there something else I could do?

**Comment by baudoinalkali** [comment]
@ogdenstudios I went ahead and merged it since there were some other elements along with it (I'll avoid this in the future), but the component in question is located here: https://github.com/baudoinalkali/newalkalisite/blob/50c8c5c9472e89136e0c6b1fd63080bfba9218aa/components/Services/FAQDropdown.tsx, the map is located here: https://github.com/baudoinalkali/newalkalisite/blob/50c8c5c9472e89136e0c6b1fd63080bfba9218aa/pages/services/web-development/wordpress-website-development.tsx#L109-L113
