### ISSUE TITLE
CLS On Header

### ISSUE THREAD

**Issue by baudoinalkali** [baudoinalkali/newalkalisite#72]
@ogdenstudios

I came across a cumulative layout shift issue on the header and ServiceHero component. It only seems to be noticeable on the prod site https://newalkalisite.vercel.app/services/web-development/wordpress-website-development, for example when you load it in you can see both the schedule a call buttons jump a bit.

**Comment by ogdenstudios** [comment]
Hey @baudoinalkali - I am a little wiped out this evening. I'll get to this over the weekend.

**Comment by ogdenstudios** [comment]
I mentioned this in #73, but [I think the remaining CLS is coming from the Next image components](https://github.com/vercel/next.js/issues/18585#issuecomment-792291602). Check the thread in #73 for my overall recommendations on how to handle that.
